DISCIPLINAS = [
    {"code": "MATM0001", "name": "ALGEBRA LINEAR", "period": 2, "prerequisites": ["MATM0007"], "corequisites": []},
    {"code": "MATM0023", "name": "CALCULO DIFERENCIAL E INTEGRAL EM UMA VARIAVEL", "period": 1, "prerequisites": [], "corequisites": []},
    {"code": "ELET0013", "name": "CIRCUITOS ELETRICOS 1", "period": 4, "prerequisites": ["FISC0034"], "corequisites": ["FISC0041"]},
    {"code": "MATM0006", "name": "COMPLEMENTOS DE MATEMATICA", "period": 4, "prerequisites": ["MATM0026"], "corequisites": ["FISC0041"]},
    {"code": "MATM0024", "name": "CÁLCULO DIFERENCIAL E INTEGRAL EM VÁRIAS VARIÁVEIS", "period": 2, "prerequisites": ["MATM0023"], "corequisites": []},
    {"code": "MATM0026", "name": "CÁLCULO DIFERENCIAL E INTEGRAL VETORIAL", "period": 3, "prerequisites": ["MATM0024"], "corequisites": []},
    {"code": "CCMP0096", "name": "CÁLCULO NUMERICO", "period": 3, "prerequisites": ["CCMP0094", "MATM0024"], "corequisites": ["MATM0026"]},
    {"code": "DPRJ0001", "name": "DCEXT DESENHO UNIVERSAL E ACESSIBILIDADE", "period": 3, "prerequisites": ["ARTE0001"], "corequisites": []},
    {"code": "SSCL0001", "name": "DCEXT SOCIOLOGIA, MEIO AMBIENTE E CONTEXTO SOCIAL CONTEMPORÂNEO", "period": 1, "prerequisites": [], "corequisites": []},
    {"code": "BASC0006", "name": "DINÂMICA", "period": 4, "prerequisites": ["FISC0067"], "corequisites": ["FISC0041"]},
    {"code": "ELET0030", "name": "ELETROMAGNETISMO 1", "period": 4, "prerequisites": ["FISC0034"], "corequisites": ["FISC0041"]},
    {"code": "ECON0001", "name": "ENGENHARIA ECONOMICA", "period": 2, "prerequisites": [], "corequisites": []},
    {"code": "FISC0041", "name": "EQUAÇÕES DIFERENCIAIS", "period": 4, "prerequisites": ["MATM0026"], "corequisites": []},
    {"code": "FISC0067", "name": "ESTÁTICA", "period": 3, "prerequisites": ["FISC0065", "MATM0007"], "corequisites": []},
    {"code": "ARTE0001", "name": "EXPRESSÃO GRÁFICA 1", "period": 2, "prerequisites": [], "corequisites": []},
    {"code": "FISC0065", "name": "FUNDAMENTOS DA MECÂNICA", "period": 2, "prerequisites": ["MATM0023"], "corequisites": []},
    {"code": "FISC0028", "name": "FUNDAMENTOS DA ONDULATÓRIA E TERMODINÂMICA", "period": 4, "prerequisites": ["FISC0034"], "corequisites": []},
    {"code": "ELET0130", "name": "FUNDAMENTOS DE CIRCUITOS ELÉTRICOS", "period": 3, "prerequisites": ["MATM0024"], "corequisites": ["FISC0034"]},
    {"code": "FISC0034", "name": "FUNDAMENTOS DO ELETROMAGNETISMO", "period": 3, "prerequisites": ["FISC0065"], "corequisites": ["MATM0026"]},
    {"code": "MATM0007", "name": "GEOMETRIA ANALITICA", "period": 1, "prerequisites": [], "corequisites": []},
    {"code": "FISC0070", "name": "INTRODUÇÃO AOS FENÔMENOS DE TRANSPORTE", "period": 4, "prerequisites": ["FISC0065", "MATM0026"], "corequisites": ["FISC0028", "FISC0041"]},
    {"code": "BASC0005", "name": "INTRODUÇÃO À ENGENHARIA ELETROTÉCNICA", "period": 1, "prerequisites": [], "corequisites": []},
    {"code": "CCMP0094", "name": "INTRODUÇÃO À PROGRAMAÇÃO", "period": 1, "prerequisites": [], "corequisites": []},
    {"code": "FISC0069", "name": "LABORATÓRIO DE FÍSICA BÁSICA", "period": 4, "prerequisites": ["FISC0034"], "corequisites": ["FISC0028"]},
    {"code": "ELET0129", "name": "MATERIAIS ELÉTRICOS", "period": 3, "prerequisites": ["QUIM0003"], "corequisites": []},
    {"code": "LETR0012", "name": "PORTUGUÊS INSTRUMENTAL", "period": 1, "prerequisites": [], "corequisites": []},
    {"code": "PRBE0005", "name": "PROBABILIDADE E ESTATISTICA", "period": 2, "prerequisites": ["MATM0023"], "corequisites": ["MATM0024"]},
    {"code": "CCMP0105", "name": "PROGRAMAÇÃO E ESTRUTURA DE DADOS", "period": 2, "prerequisites": ["CCMP0094"], "corequisites": []},
    {"code": "QUIM0003", "name": "QUIMICA", "period": 1, "prerequisites": [], "corequisites": []}
] 