DISCIPLINAS = [
    {"code": "LETR0007", "name": "ACESSIBILIDADE E LIBRAS", "period": 9, "prerequisites": [], "corequisites": [], "hours": 45, "credits": 3.0},
    {"code": "ELET0001", "name": "ACIONAMENTO DE MAQUINAS ELÉTRICAS", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0005", "name": "ANALISE DE SISTEMA DE POTENCIA 3", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0008", "name": "AUTOMAÇÃO DE SISTEMAS ELETRICOS", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0089", "name": "COMERCIALIZAÇÃO DE ENERGIA", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0017", "name": "COMPENSAÇÃO DE REATIVOS EM SISTEMAS ELETRICOS", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0024", "name": "CONTROLE DE PROCESSOS", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "MECN0115", "name": "DCEXT INTELIGÊNCIA ARTIFICIAL", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "MECN0104", "name": "DCEXT MECANISMOS", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0138", "name": "DCEXT-EFICIÊNCIA ENERGÉTICA", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "CCMP0106", "name": "DCEXT-FERRAMENTAS COMPUTACIONAIS PARA ENGENHARIA", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0093", "name": "DCEXT-PRINCIPIOS DE INSTRUMENTOS BIOMÉDICOS", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0043", "name": "FONTES ALTERNATIVAS DE ENERGIA", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0059", "name": "OPERACAO DE MAQUINAS ELETRICAS", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0060", "name": "PLANEJAMENTO DOS SISTEMAS ELETRICOS", "period": 9, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0069", "name": "QUALIDADE DE ENERGIA ELETRICA", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0155", "name": "SISTEMAS DE ARMAZENAMENTO DE ENERGIA", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0096", "name": "TRANSITÓRIO MAQUINAS ELETRICAS", "period": 10, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0}
] 
