DISCIPLINAS = [
    {"code": "ELET0003", "name": "ANALISE DE SISTEMA DE POTENCIA 1", "period": 7, "prerequisites": ["ELET0025"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0004", "name": "ANALISE DE SISTEMA DE POTENCIA 2", "period": 8, "prerequisites": ["ELET0003"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0014", "name": "CIRCUITOS ELETRICOS 2", "period": 5, "prerequisites": ["ELET0013"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0025", "name": "CONVERSÃO ELETROMECANICA DE ENERGIA", "period": 6, "prerequisites": ["ELET0014", "ELET0031"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "DIRT0001", "name": "DIREITO PARA ENGENHEIROS", "period": 7, "prerequisites": ["ECON0001"], "corequisites": [], "hours": 30, "credits": 2.0},
    {"code": "ELET0029", "name": "DISTRIBUICAO DE ENERGIA ELETRICA", "period": 9, "prerequisites": ["ELET0004"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0031", "name": "ELETROMAGNETISMO 2", "period": 5, "prerequisites": ["ELET0030"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0033", "name": "ELETRONICA 1", "period": 5, "prerequisites": [], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0035", "name": "ELETRONICA ANALÓGICA", "period": 6, "prerequisites": ["ELET0014", "ELET0033"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0037", "name": "ELETRONICA DIGITAL", "period": 5, "prerequisites": ["ELET0013"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0039", "name": "ELETROTECNICA 1", "period": 6, "prerequisites": ["ELET0014", "ELET0129", "ELET0130"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0101", "name": "ELETROTECNICA 2", "period": 7, "prerequisites": ["ELET0039"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0152", "name": "ELETRÔNICA DE POTÊNCIA 2", "period": 8, "prerequisites": ["ELET0025", "ELET0075", "ELET0151"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0151", "name": "ELETRÔNICA DE POTÊNCIA I", "period": 7, "prerequisites": ["ELET0035", "ELET0037"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ENGE0001", "name": "ENGENHARIA DE SEGURANCA", "period": 6, "prerequisites": ["ELET0014"], "corequisites": [], "hours": 45, "credits": 3.0},
    {"code": "ELET0040", "name": "EQUIPAMENTOS ELETRICOS", "period": 8, "prerequisites": ["ELET0003", "ELET0129"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0041", "name": "ESTAGIO SUPERVISIONADO", "period": 8, "prerequisites": ["ENGE0001"], "corequisites": [], "hours": 180, "credits": 12.0},
    {"code": "ELET0044", "name": "GERACAO DE ENERGIA ELETRICA", "period": 9, "prerequisites": ["ELET0051"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0137", "name": "GESTÃO ORGANIZACIONAL PARA ENGENHEIROS", "period": 7, "prerequisites": ["SSCL0001"], "corequisites": [], "hours": 30, "credits": 2.0},
    {"code": "ELET0046", "name": "INSTRUMENTACAO", "period": 8, "prerequisites": ["ELET0035", "ELET0078"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0047", "name": "LABORATORIO DE ELETRONICA 1", "period": 5, "prerequisites": ["ELET0013"], "corequisites": ["ELET0033"], "hours": 30, "credits": 2.0},
    {"code": "ELET0134", "name": "LABORATORIO DE ELETRÔNICA ANALÓGICA E DIGITAL", "period": 7, "prerequisites": ["ELET0035", "ELET0037"], "corequisites": [], "hours": 30, "credits": 2.0},
    {"code": "ELET0051", "name": "MAQUINAS ELETRICAS", "period": 8, "prerequisites": ["ELET0025"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0156", "name": "MAQUINAS PRIMÁRIAS", "period": 5, "prerequisites": ["FISC0070"], "corequisites": [], "hours": 30, "credits": 2.0},
    {"code": "ELET0054", "name": "MEDIDAS ELETRICAS", "period": 6, "prerequisites": ["ELET0014"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0055", "name": "MERCADO DE ENERGIA ELETRICA", "period": 5, "prerequisites": ["PRBE0005"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0150", "name": "METODOLOGIA CIENTÍFICA E INOVAÇÃO TECNOLÓGICA EM ENGENHARIA ELETROTÉCNICA", "period": 6, "prerequisites": ["ELET0130", "LETR0012"], "corequisites": [], "hours": 30, "credits": 2.0},
    {"code": "ELET0153", "name": "PROJETO FINAL DE ENGENHARIA ELETROTÉCNICA", "period": 9, "prerequisites": ["ELET0004", "ELET0150"], "corequisites": [], "hours": 30, "credits": 2.0},
    {"code": "ELET0067", "name": "PROTECAO DE SISTEMAS ELETRICOS", "period": 9, "prerequisites": ["ELET0004"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0149", "name": "RESISTÊNCIA DOS MATERIAIS", "period": 5, "prerequisites": ["BASC0006"], "corequisites": [], "hours": 45, "credits": 3.0},
    {"code": "ELET0075", "name": "SISTEMA DE CONTROLE 1", "period": 6, "prerequisites": ["ELET0014", "FISC0041", "MATM0006"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0076", "name": "SISTEMA DE CONTROLE 2", "period": 7, "prerequisites": ["ELET0075"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0078", "name": "SISTEMAS DIGITAIS", "period": 6, "prerequisites": ["ELET0037"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0080", "name": "SUBESTACÕES", "period": 9, "prerequisites": ["ELET0003", "ELET0040"], "corequisites": [], "hours": 60, "credits": 4.0},
    {"code": "ELET0098", "name": "TRANSMISSAO DE ENERGIA ELETRICA", "period": 9, "prerequisites": ["ELET0004"], "corequisites": [], "hours": 60, "credits": 4.0}
] 
